### ISSUE TITLE
Null reference on ReadCookie and sharing classes between projects

### ISSUE THREAD

**Issue by bdominguez** [yasinkuyu/Localization#10]
I have a big solution with multiple projects. The output are managed by two projects: an ASP MVC application and a WPF application.

There is a datamodel project shared between them with "DisplayLocalized" attribute in them. My problem is that when in the WPF application is instantiated any data model class, it throws a NullReferenceException on "ReadCookie" method because "HttpContext.Current" is null.

Can your return the original "id" like you do when there are no results for that "id"? That way it should not crash and since in WPF I don't use that attribute it doesn't matter.

I can do it myself but since I'm using your nuget package, it's a pain to deal with that because if there is an update in your package it will broke my project again.

**Comment by yasinkuyu** [comment]
You can make the necessary arrangements . Then please send pull-request .

**Comment by bdominguez** [comment]
I don't know how to do a pull request, I don't use Git.

It's an easy change, could you do it please? I can help you if you want but I don't know how to make a pull request.

**Comment by yasinkuyu** [comment]
Sorry. I do not know how I can help you go if you do not use.
