### ISSUE TITLE
Inherit

### ISSUE THREAD

**Issue by HKhedr** [yasinkuyu/Localization#11]
Hello.
Thank you for great nuget that help me.
But I'm try add ar = "" to inline code but not working  
public class ARInline : Inline
    {
        public ARInline() { }
        public ARInline(string ar = "", string en = ""){ }
        public string ar_SA { get; set; }
    }

regards.

**Comment by yasinkuyu** [comment]
Hello,

Incorrect Interface (Inline to IInline)

public class ARInline : **IInline**

https://github.com/yasinkuyu/Localization/blob/Haster/src/IInline.cs

**Comment by HKhedr** [comment]
I know that I Inherit from class Inline because when I Inherit from interface IInline I get that error 
Interface IInline is inaccessible due to its protection level.

Regards

**Comment by HKhedr** [comment]
How can I make update in nuget ??

Regards

**Comment by yasinkuyu** [comment]
It's a long thread.

I will give information when I Nuget update.
