### ISSUE TITLE
Çerezi elle değiştirince hata

### ISSUE THREAD

**Issue by erenguler** [yasinkuyu/Localization#16]
System.IO.FileNotFoundException:
WEB.UI\Localization\deger_DEGER.xml' dosyası bulunamadı.

varsayılan dile yönlendirebilir...

**Comment by yasinkuyu** [comment]
Default locale değeri değiştirmek için newCookie.Value = "en_US"; satırını değiştirebilirsiniz.

Localization klasöründe olmayan bir dil seti tanımlarsan FileNotFoundException hatası döner.
https://github.com/yasinkuyu/Localization/blob/Haster/src/Resource.cs

newCookie.Value = "tr_TR" ise Localization klasöründe tr_TR.xml isminde dil dosyası olmalı.

public void DefaultLocale( )
{
    HttpCookie cookie = Request.Cookies.Get("CacheLang");
    if ( cookie == null)
    {
        HttpCookie newCookie = new HttpCookie("CacheLang");
        newCookie.Value = "en_US";
        Response.Cookies.Add(newCookie);
    }
}
