### ISSUE TITLE
Set the default language

### ISSUE THREAD

**Issue by lgkonline** [yasinkuyu/Localization#3]
First I want to thank you for this great plugin.
Is there a way to change the default language?

**Comment by irutz** [comment]
Thanks also from me. It's a very great plugin. 
Is there any way to load another language file by default then en_US?

**Comment by yasinkuyu** [comment]
main controller define this cookie.

Response.Cookies["CacheLang"].Value = "en_US;

Ex;

```
        HttpCookie cookie = Request.Cookies.Get("CacheLang");
        if ( cookie == null)
        {
            HttpCookie newCookie = new HttpCookie("CacheLang");
            newCookie.Value = "en_US";
            Response.Cookies.Add(newCookie);
        }
```
