### ISSUE TITLE
XML comment lines

### ISSUE THREAD

**Issue by geriremenyi** [yasinkuyu/Localization#6]
Null reference error when using comment tags () in the language XML files.

**Comment by yasinkuyu** [comment]
&lt;detail&gt;
     &lt;band height=&quot;20&quot;&gt;
     &lt;!--
       Hello,
          I am a multi-line XML comment
          &lt;staticText&gt;
             &lt;reportElement x=&quot;180&quot; y=&quot;0&quot; width=&quot;200&quot; height=&quot;20&quot;/&gt;
             &lt;text&gt;&lt;![CDATA[Hello World!]]&gt;&lt;/text&gt;
           &lt;/staticText&gt;
      --&gt;
     &lt;/band&gt;
&lt;/detail&gt;
