### ISSUE TITLE
get the id

### ISSUE THREAD

**Issue by manumarenco** [yasinkuyu/Localization#7]
Hi,
I always get the ID, in my bar menu the first time that I load the web, instead of the content of the ID. 
Only when I refresh the web, I get all the translations.
Can I fix this in any way? 

Thank you very much!

![image](https://cloud.githubusercontent.com/assets/8057971/11899233/e4fd8964-a59d-11e5-856b-a84e9f39588b.png)

**Comment by manumarenco** [comment]
Hi @yasinkuyu?? Can you help me please? :)

**Comment by yasinkuyu** [comment]
Check id name defined in XML. 

@Html.Get("menubar_home")

&lt;lang&gt;
    &lt;item id=&quot;menubar_home&quot;&gt;Menu Home&lt;/item&gt;
&lt;/lang&gt;

**Comment by manumarenco** [comment]
Hi!! 
Thank you for your answers. But, yes....of course I checked the ID in the xml. In fact, it´s only the first time I load the web, if I press f5, I can see every item correctly

**Comment by yasinkuyu** [comment]
Set the default language. https://github.com/yasinkuyu/Localization/issues/3
