### ISSUE TITLE
Where to put DefaultLocale( ) method?

### ISSUE THREAD

**Issue by tomikapc** [yasinkuyu/Localization#9]
I don't really know where to put the DefaultLocale( ) method I could find in the Readme. I've installed the 1.0.7 version, then I upgraded it to 1.0.8 with nuget.

I have a controller which looks like this now:

`
public class LocalesController : Controller
    {

```
    public ActionResult Index(string lang = "hu_HU")
    {
        Response.Cookies["CacheLang"].Value = lang;

        if (Request.UrlReferrer != null)
            Response.Redirect(Request.UrlReferrer.ToString());

        var message = Localization.Get("changedlng");

        return Content(message);
    }



}
```

`

But the default language for the site is still english.

Can you specify where to modify the code to set another default language?

Thank you very much!

**Comment by yasinkuyu** [comment]
https://github.com/yasinkuyu/Localization/issues/3
